title: "Siobhan Devaney"
description: >
  Siobhan Devaney is a fiction writer whose stories explore the emotional edges of everyday life.

remote_theme: pmarsceill/just-the-docs
color_scheme: light

collections:
  blog:
    output: true
    directory: _blog
    permalink: /blog/:name/

just_the_docs:
  nav:
    - title: "ğŸ  Home"
      url: "/"
    - title: "ğŸª¶ About"
      url: "/about/"
    - title: "ğŸ“ Blog"
      url: "/blog/"
    - title: "ğŸ“¬ Contact"
      url: "/contact/"

  include_head:
    - head-custom.html

search_enabled: false

favicon_ico: "/assets/images/favicon.ico"

url: "https://formisfate.github.io"       # Fill in if deploying
baseurl: "/siobhandevaney"   # Fill in if deploying
