title: "Siobhan Devaney"
description: >
  Australian fiction writer and essayist exploring the strange and emotional edges of human nature.

remote_theme: pmarsceill/just-the-docs
color_scheme: light

collections:
  pages:
    output: true
    directory: _pages
    permalink: /:path/

just_the_docs:
  nav:
    - title: "ğŸ  Home"
      url: "/"
    - title: "ğŸ“ About"
      url: "/about/"
    - title: "ğŸ“š Writing"
      url: "/writing/"
    - title: "ğŸ“¬ Contact"
      url: "/contact/"

  include_head:
    - head_custom.html

url: "https://formisfate.github.io"
baseurl: "/siobhan-site"

search_enabled: true
favicon_ico: "/assets/images/favicon.ico"

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
